name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Extract version name
        id: extract_name
        run: echo "name=$(echo ${GITHUB_REF##*/})" >>$GITHUB_OUTPUT
        shell: bash

      - name: Checkout to push branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.extract_name.outputs.name }}
          body: ${{ steps.changelog.outputs.changelog }}

  build-web:
    name: Build web release
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout to push branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build Wasm Distribution
        if: job.status == 'success'
        run: |
          export GRADLE_USER_HOME=$(pwd)/.gradle
          chmod +x ./gradlew
          ./gradlew composeApp:wasmJsBrowserDistribution

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./composeApp/build/dist/wasmJs/productionExecutable
          force_orphan: true
          cname: runman.procyk.in
